// AUTH
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const AUTH_ERROR = 'AUTH_ERROR';

// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// DEPARTMENTS
export const ALL_DEPARTMENTS_LOADED = 'ALL_DEPARTMENTS_LOADED';
export const DEPARTMENT_LOADED = 'DEPARTMENT_LOADED';
export const DEPARTMENT_CREATED = 'DEPARTMENT_CREATED';
export const DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED';
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR';

// PROGRAMS
export const ALL_PROGRAMS_LOADED = 'ALL_PROGRAMS_LOADED';
export const PROGRAM_LOADED = 'PROGRAM_LOADED';
export const PROGRAM_CREATED = 'PROGRAM_CREATED';
export const PROGRAM_UPDATED = 'PROGRAM_UPDATED';
export const PROGRAM_ERROR = 'PROGRAM_ERROR';
